[project]
name = "py-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.1",
    "maturin>=1.10.1",
    "setuptools>=80.9.0",
]
