[package]
name = "pyo3"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "str_compare"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
rayon = "1.11" # 使用一个稳定的版本